title: terminal
font:
  normal:
    family: Cartograph CF Extra Light
    style: Regular
  bold:
    family: Cartograph CF Heavy
    style: Bold
  italic:
    family: Cartograph CF Italic
    style: Italic
  bold_italic:
    family: Cartograph CF Bold Italic
    # style: Bold Italic
  size: 14
key_bindings:
  - action: Paste
    key: Paste
  - action: Copy
    key: Copy
  - action: Paste
    key: V
    mode: ~Vi
    mods: Alt
  - action: Copy
    key: C
    mods: Alt
colors:
  # Default colors
  primary:
    background: '0x282935'
    foreground: '0xefefea'
  # Normal colors
  normal:
    black:   '#a5aad9'
    red:     '0xF07178'
    green:   '0xC3E88D'
    yellow:  '0xd9bb80'
    blue:    '0x89beba'
    magenta: '0xd3a0bc'
    cyan:    '0x87c095'
    white:   '0x868d80'

  # Bright colors
  bright:
    black:   '0x5f747f'
    red:     '0xe68183'
    green:   '0xa7c080'
    yellow:  '0xd9bb80'
    blue:    '0x89beba'
    magenta: '0xd3a0bc'
    cyan:    '0x87c095'
    white:   '0x868d80'

  selection:
      background: '0x2d4f67'
      foreground: '0xc8c093'

  indexed_colors:
    - { index: 16, color: '0xffa066' }
    - { index: 17, color: '0xff5d62' }
allow_executables:
  - nvim
term:
  env:
    NVIM_LISTEN_ADDRESS: /tmp/nvimsocket
env:
  TERM: xterm-256color

shell:
  # program: /usr/bin/env
  # args:
    # - SHELL=/bin/sh
    # - -c
    # - "nvim +{line} {file}"

  # args:
    # - +{line}
    # - {file}

window:
  decorations: full
  dynamic_title: true
  opacity: 1
  padding:
    x: 5
    y: 2 
