#!/usr/bin/env bash

export PATH=$PATH:~/.local/bin:~/dot-files/bin:~/Documents/androide/platform-tools/:~/.fly/bin/

# Configuration pyenv
# export PYENV_ROOT="$HOME/.pyenv"
# export PATH="$PYENV_ROOT/bin:$PATH"
# export WORKON_HOME=$HOME/.virtualenvs
#export PROJECT_HOME=$HOME/repo/prj
if command -v pyenv 1>/dev/null 2>&1; then
	eval "$(pyenv init --path)"
fi
# eval "$(pyenv init --path)"
# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"

# export PYENV_VIRTUALENV_DISABLE_PROMPT=1

# Most pure GTK3 apps use wayland by default, but some,
# like Firefox, need the backend to be explicitely selected.
export MOZ_ENABLE_WAYLAND=1
export MOZ_DBUS_REMOTE=1
export GTK_CSD=0

# qt wayland
export QT_QPA_PLATFORM="wayland"
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_WAYLAND_DISABLE_WINDOWDECORATION="1"

#Java XWayland blank screens fix
export _JAVA_AWT_WM_NONREPARENTING=1

#export CLUTTER_BACKEND=wayland
#export GDK_BACKEND=x11,wayland,x11
#export XDG_SESSION_TYPE=wayland
# export XDG_CURRENT_DESKTOP=sway
# firefox
#export MOZ_ENABLE_WAYLAND=1
#export JAVA_HOME=/home/yoser/.asdf/installs/java/openjdk-13

#. ~/.asdf/plugins/java/set-java-home.zsh
LC_CTYPE=en_US.UTF-8
LC_ALL=en_US.UTF-8
# export LANG="en_US.UTF-8"
# export LC_ALL="en_US.UTF-8"
# export LC_CTYPE="en_US.UTF-8"
# export LANGUAGE="en_US.UTF-8"
#export LC_COLLATE="en_US.UTF-8"
#export LC_TIME="es_CO.UTF-8"
#export LC_NUMERIC="en_CO.UTF-8"
#export LC_MONETARY="es_CO.UTF-8"
#export LC_MESSAGES="en_US.UTF-8"

#export TERM="tmux-256color"
export TERM_ITALICS=true
export COLORTERM='truecolor'
#if  [[ $(tty) != /dev/tty1 ]]; then
#tmux -2
#fi

###enviroment to work
export mono_cert="mono-cert-eks"
export mono_prod="mono-prod-eks"
export mono_sdbx="mono-sdbx-eks"

if [ -f /tmp/first ]; then
else
	fortune | cowsay -f $(ls /usr/share/cows/ | shuf -n1) -n
	touch /tmp/first
	printf "%s " "Press enter to continue"
	read a
fi
