#!/usr/bin/env bash

export PATH=$PATH:~/.local/bin:~/dot-files/bin:~/src/liftit/geolib:~/Documents/androide/platform-tools/:~/.asdf/shims

# Configuration pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export WORKON_HOME=$HOME/.virtualenvs
#export PROJECT_HOME=$HOME/repo/prj
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
fi
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

export PYENV_VIRTUALENV_DISABLE_PROMPT=1

export TERM_ITALICS=true

export _JAVA_AWT_WM_NONREPARENTING=1
export CLUTTER_BACKEND=wayland
export GDK_BACKEND=wayland,x11
#export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=sway
# firefox
#export MOZ_ENABLE_WAYLAND=1
#export JAVA_HOME=/home/yoser/.asdf/installs/java/openjdk-13

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash
#. ~/.asdf/plugins/java/set-java-home.zsh
export LANG="es_CO.UTF-8"
export LC_CTYPE="es_CO.UTF-8"
#export LC_COLLATE="en_US.UTF-8"
#export LC_TIME="es_CO.UTF-8"
#export LC_NUMERIC="en_CO.UTF-8"
#export LC_MONETARY="es_CO.UTF-8"
#export LC_MESSAGES="en_US.UTF-8"

#export TERM="tmux-256color"
export COLORTERM='truecolor'
if  [[ $(tty) != /dev/tty1 ]]; then
	tmux -2
fi

