#!/bin/bash
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#676676,bold"
CASE_SENSITIVE="true"
ZSH_AUTOSUGGEST_USE_ASYNC='true'
#ZSH_TMUX_AUTOSTART='true'

if [[ $(tty) = /dev/tty1 ]]
  then
    initx=startx
else
    initx=""
    ZSH_THEME="agnoster"
fi
# Uncomment the following line to disable bi-weekly auto-update checks.
#DISABLE_AUTO_UPDATE="true"

plugins=(
  git
  z
  tmux
  vi-mode
  copypath
  colorize
  copybuffer
  zsh-autosuggestions
  zsh-syntax-highlighting
  colored-man-pages
)



ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh
if [[ ! -d $ZSH_CACHE_DIR ]]; then
  mkdir $ZSH_CACHE_DIR
fi

bindkey -v
bindkey "^R" history-incremental-search-backward

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/.fzf/shell/key-bindings.zsh

source ~/.fzf/shell/completion.zsh

[ -f /usr/share/zsh/site-functions/git-flow-completion.zsh ] \
	&& source /usr/share/zsh/site-functions/git-flow-completion.zsh

# tabtab source for electron-forge package
# uninstall by removing these lines or running `tabtab uninstall electron-forge`
[[ -f /home/yoser/.cache/yay/httptoolkit/src/httptoolkit/node_modules/tabtab/.completions/electron-forge.zsh ]] && . /home/yoser/.cache/yay/httptoolkit/src/httptoolkit/node_modules/tabtab/.completions/electron-forge.zsh

compdef __start_kubectl k

source $ZSH/oh-my-zsh.sh
source ~/dot-files/bash_aliases
source ~/dot-files/bash_export
source ~/dot-files/bash_hotkeys

if [[ $initx != "" ]]
    then
#  export XDG_SESSION_DESKTOP=sway
  #export XDG_CURRENT_DESKTOP=sway
  #export XDG_SESSION_TYPE=wayland
  #export QT_QPA_PLATFORM="wayland"
  #export QT_QPA_PLATFORMTHEME=qt5ct
  #export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
  #sway -d > /tmp/sway.log
#  exec sway > /tmp/sway.log 2>&1
# $initx
else 
  tmux -2
fi

function mix_test () {(source .env.test && mix $@);}
