#!/bin/bash
ZSH=/usr/share/oh-my-zsh

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#676676,bold"
CASE_SENSITIVE="true"
ZSH_AUTOSUGGEST_USE_ASYNC='true'
#ZSH_TMUX_AUTOSTART='true'

if [[ $(tty) = /dev/tty1 ]]; then
	# initx=wayland
	#startx
else
	initx=""
	ZSH_THEME="eastwood"
fi
# Uncomment the following line to disable bi-weekly auto-update checks.
#DISABLE_AUTO_UPDATE="true"

plugins=(
	git
	z
	tmux
	vi-mode
	copypath
	colorize
	copybuffer
	zsh-autosuggestions
	zsh-syntax-highlighting
	colored-man-pages
)

ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh
if [[ ! -d $ZSH_CACHE_DIR ]]; then
	mkdir $ZSH_CACHE_DIR
fi

bindkey -v
bindkey "^R" history-incremental-search-backward

if [ -f ~/.fzf.zsh ]; then
	source ~/.fzf.zsh
	source ~/.fzf/shell/key-bindings.zsh
	source ~/.fzf/shell/completion.zsh
fi

[ -f /usr/share/zsh/site-functions/git-flow-completion.zsh ] &&
	source /usr/share/zsh/site-functions/git-flow-completion.zsh

# tabtab source for electron-forge package
#uninstall by removing these lines or running `tabtab uninstall electron-forge`
[[ -f /home/yoser/.cache/yay/httptoolkit/src/httptoolkit/node_modules/tabtab/.completions/electron-forge.zsh ]] && . /home/yoser/.cache/yay/httptoolkit/src/httptoolkit/node_modules/tabtab/.completions/electron-forge.zsh

eval "$(mise activate zsh)"
#compdef __start_kubectl k

source $ZSH/oh-my-zsh.sh
source ~/dot-files/bash_aliases
source ~/dot-files/bash_export
source ~/dot-files/bash_hotkeys

if [[ $initx != "" ]]; then
	export HYPRLAND_LOG_WLR=1
	export XCURSOR_THEME=Bibata-Modern-Classic

	# Set a cursor size
	export XCURSOR_SIZE=24
	echo "iniciando interfaz grafica"
	Hyprland
	# dbus-run-session -- "$HOME"/Hyprland/build/src/Hyprland
	# export XDG_SESSION_DESKTOP=sway
	# export XDG_CURRENT_DESKTOP=sway
	# export XDG_SESSION_TYPE=wayland
	# export QT_QPA_PLATFORM="wayland-egl"
	# export QT_QPA_PLATFORMTHEME=qt5ct
	# export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
	# export WLR_WL_OUTPUTS=2
	# export MOZ_ENABLE_WAYLAND=1
	#export WAYLAND_DISPLAY="wayland-0"
	#
	#echo 0x19F | sudo tee /sys/module/drm/parameters/debug # Enable verbose DRM logging
	#sudo dmesg -C # Clear kernel logs
	#dmesg -w >dmesg.log & # Continuously write DRM logs to a file, in the background
	# exec sway -d >>/tmp/sway.log 2>&1 # Reproduce the bug, then exit sway
	#
	##
	#---XDG_SESSION_TYPE=wayland dbus-run-session /usr/bin/gnome-shell
	#
	# exec dbus-run-session sway
	# $initx
else
fi

function mix_test() { (source .env.test && mix $@); }
